name: nodejs

on:
  push:
    paths:
      - "samples/nodejs/*"
      - ".github/workflows/nodejs.yml"

env:
  DOCKER_REGISTRY: docker.pkg.github.com
  USER: ${{ secrets.USER }}
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
  OWNER: miracl

jobs:
  lint-nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Run eslint
        run: |
          npm install --prefix samples/nodejs
          npm run eslint:action --prefix samples/nodejs

  build-docker:
    needs: lint-nodejs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Docker login, build & push
        run: |
          docker login -u $USER -p $AUTH_TOKEN $DOCKER_REGISTRY
          docker build --tag $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest samples/nodejs/
          docker push $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest
          docker tag $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:$GITHUB_ACTION
          docker push $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:$GITHUB_ACTION

  run-integration-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

        run: |
          docker login -u $USER -p $AUTH_TOKEN $DOCKER_REGISTRY
          docker pull $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest
          SAMPLE_CONTAINER_ID=$(docker run -d -p 8000:8000 --rm -e CLIENT_ID -e CLIENT_SECRET $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest)
          docker run --network="host" --rm -e CLIENT_ID -e CLIENT_SECRET $DOCKER_REGISTRY/$OWNER/oidc-samples/integration-tests:latest
          docker container stop $SAMPLE_CONTAINER_ID

  run-no-mitm-integration-tests:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Run integration tests through proxy, without MITM
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

        run: |
          docker login -u $USER -p $AUTH_TOKEN $DOCKER_REGISTRY
          PROXY_CONTAINER_ID=$(docker run -d -p 8080:8080 --rm $DOCKER_REGISTRY/$OWNER/oidc-samples/proxy:latest)
          SAMPLE_CONTAINER_ID=$(docker run --network host -d --rm -e CLIENT_ID -e CLIENT_SECRET -e PROXY_HOST=127.0.0.1 -e PROXY_PORT=8080 $DOCKER_REGISTRY/$OWNER/oidc-samples/nodejs:latest)
          docker run --network="host" --rm -e CLIENT_ID -e CLIENT_SECRET $DOCKER_REGISTRY/$OWNER/oidc-samples/integration-tests:latest
          docker container stop $SAMPLE_CONTAINER_ID
          docker container stop $PROXY_CONTAINER_ID
